"""SpeechJudge-Data streaming loader.

Yields one decoded audio clip at a time from the live HuggingFace dataset.
Each preference pair contributes TWO clips (audioA + audioB), each emitted
as a separate `ClipRecord` so the downstream feature extractor and cache
deal in flat units.

Why not yield pairs directly: the BT training loop assembles pairs from the
feature cache by `pair_id`, so the cache lookup needs per-clip granularity.
Keeping the loader flat also makes resume-from-checkpoint trivial (one
manifest entry per clip).

Why we bypass `datasets.load_dataset` for audio: the Audio() feature in
datasets>=4.8 streaming mode silently ignores cast_column(decode=False) --
the formatter keeps the original decode=True schema and pulls in torchcodec
(which requires libavutil.so.56, i.e. system ffmpeg). To stay portable we
read parquet shards directly via huggingface_hub + pyarrow, then decode the
inline bytes with soundfile. Same fields, no decoder dep.

Schema this loader knows about is documented in docs/DATASETS.md, which was
auto-generated by scripts/00_inspect_dataset.py during Milestone 1.
"""

from __future__ import annotations

import io
import re
from dataclasses import dataclass
from typing import Iterator, Literal

import numpy as np

DATASET_ID = "RMSnow/SpeechJudge-Data"
Side = Literal["A", "B"]
SPLITS = ("train", "dev", "test")
_SHARD_RE = re.compile(r"^(?P<split>train|dev|test|other)-\d+-of-\d+\.parquet$")


@dataclass(frozen=True)
class ClipRecord:
    """One audio clip from a SpeechJudge preference pair, pre-decoded."""

    pair_index: int                # row index across the concatenated split
    side: Side                     # "A" or "B"
    subset: str                    # "regular" | "expressive"
    language_setting: str          # e.g. "zh2en"
    target_text: str               # text both A and B synthesize
    waveform: np.ndarray           # float32, mono, native sample rate
    sample_rate: int

    @property
    def clip_id(self) -> str:
        return f"{self.pair_index:08d}_{self.side}"

    def num_samples(self) -> int:
        return int(self.waveform.shape[0])

    def duration_seconds(self) -> float:
        return self.num_samples() / float(self.sample_rate)


def _list_split_shards(split: str, *, token: str | None) -> list[str]:
    """Return repo-relative parquet filenames for a split, in shard order."""
    from huggingface_hub import HfApi

    files = HfApi(token=token).list_repo_files(DATASET_ID, repo_type="dataset")
    shards: list[tuple[int, str]] = []
    for f in files:
        m = _SHARD_RE.match(f)
        if not m or m.group("split") != split:
            continue
        shard_idx = int(f.split("-")[1])
        shards.append((shard_idx, f))
    shards.sort()
    return [f for _, f in shards]


def _decode_audio_struct(struct: dict) -> tuple[np.ndarray, int]:
    """Decode the HF Audio({path, bytes}) dict via soundfile."""
    import soundfile as sf

    raw = struct.get("bytes")
    path = struct.get("path")
    if raw is None:
        raise ValueError(
            f"Audio dict has no inline bytes (path={path!r}). "
            "M1 inspection promised inline bytes; the dataset schema may have changed."
        )
    wav, sr = sf.read(io.BytesIO(raw), dtype="float32", always_2d=False)
    if wav.ndim == 2:
        wav = wav.mean(axis=1).astype(np.float32, copy=False)
    return wav, int(sr)


@dataclass(frozen=True)
class PairRecord:
    """One full SpeechJudge preference pair, both clips decoded.

    Used by the online-streaming training path (Kaggle T4) where we
    don't pre-extract Whisper features to disk -- we run the encoder
    forward as part of the training step instead.
    """

    pair_index: int
    subset: str                              # "regular" | "expressive"
    language_setting: str                    # "zh2en", "en2en", ...
    target_text: str
    audio_a: np.ndarray                      # float32 mono
    audio_b: np.ndarray
    sample_rate_a: int
    sample_rate_b: int
    naturalness_label: str                   # "A" or "B"
    naturalness_annotation: list[str]        # e.g. ["B+2", "B+1"]
    chosen: bool                             # high-rater-agreement flag


def iter_pairs(
    split: str = "train",
    limit: int | None = None,
    *,
    token: str | None = None,
    skip: int = 0,
    shuffle_shards: bool = False,
    shard_seed: int = 0,
) -> Iterator[PairRecord]:
    """Stream-decode SpeechJudge as full pairs (both audio sides + labels).

    Designed for online training: each PairRecord has everything the
    training step needs, in a single emit. No separate pair_meta sidecar
    required.

    Args:
        split: dataset split, one of {"train", "dev", "test"}.
        limit: max pairs to yield. None = full split.
        token: HF token; reads from env if None.
        skip: pairs to skip from the start (resume / sharding).
        shuffle_shards: if True, randomise shard visit order (epoch-level
            shuffle that doesn't blow memory on the in-shard ordering).
        shard_seed: rng seed for shard shuffle.
    """
    if split not in SPLITS:
        raise ValueError(f"split={split!r} not in {SPLITS}")

    import random

    import pyarrow.parquet as pq
    from huggingface_hub import hf_hub_download

    shards = _list_split_shards(split, token=token)
    if not shards:
        raise RuntimeError(f"No parquet shards found for split {split!r} in {DATASET_ID}")
    if shuffle_shards:
        rng = random.Random(shard_seed)
        shards = list(shards)
        rng.shuffle(shards)

    yielded = 0
    rows_seen = 0
    for shard_name in shards:
        if limit is not None and yielded >= limit:
            break
        local = hf_hub_download(
            repo_id=DATASET_ID, filename=shard_name,
            repo_type="dataset", token=token,
        )
        parquet = pq.ParquetFile(local)
        for rg_idx in range(parquet.num_row_groups):
            if limit is not None and yielded >= limit:
                break
            table = parquet.read_row_group(rg_idx)
            for row in table.to_pylist():
                if rows_seen < skip:
                    rows_seen += 1
                    continue
                if limit is not None and yielded >= limit:
                    break
                wav_a, sr_a = _decode_audio_struct(row["audioA"])
                wav_b, sr_b = _decode_audio_struct(row["audioB"])
                yield PairRecord(
                    pair_index=rows_seen,
                    subset=row.get("subset", "") or "",
                    language_setting=row.get("language_setting", "") or "",
                    target_text=row.get("target_text", "") or "",
                    audio_a=wav_a, audio_b=wav_b,
                    sample_rate_a=sr_a, sample_rate_b=sr_b,
                    naturalness_label=row.get("naturalness_label", "") or "",
                    naturalness_annotation=row.get("naturalness_annotation") or [],
                    chosen=bool(row.get("chosen", False)),
                )
                rows_seen += 1
                yielded += 1


def iter_clips(
    split: str = "train",
    limit: int | None = None,
    *,
    token: str | None = None,
    skip: int = 0,
    sides: tuple[Side, ...] = ("A", "B"),
) -> Iterator[ClipRecord]:
    """Stream-decode SpeechJudge clips.

    Args:
        split: dataset split, one of {"train", "dev", "test"}.
        limit: maximum number of PAIRS to yield (each contributes len(sides)
               clips). None = no limit.
        token: HF token; reads from env if None.
        skip: number of pairs to skip from the start of the split (for
              resume-from-checkpoint or sharding).
        sides: which sides to yield. Default both; ("A",) for one-sided runs.
    """
    if split not in SPLITS:
        raise ValueError(f"split={split!r} not in {SPLITS}")
    if any(s not in ("A", "B") for s in sides):
        raise ValueError(f"sides must contain only 'A'/'B'; got {sides!r}")

    import pyarrow.parquet as pq
    from huggingface_hub import hf_hub_download

    shards = _list_split_shards(split, token=token)
    if not shards:
        raise RuntimeError(f"No parquet shards found for split {split!r} in {DATASET_ID}")

    yielded_pairs = 0
    rows_seen = 0
    for shard_name in shards:
        if limit is not None and yielded_pairs >= limit:
            break

        local = hf_hub_download(
            repo_id=DATASET_ID,
            filename=shard_name,
            repo_type="dataset",
            token=token,
        )
        # Open lazily, iterate row-groups so we don't pull the whole shard
        # into memory at once.
        parquet = pq.ParquetFile(local)
        for rg_idx in range(parquet.num_row_groups):
            if limit is not None and yielded_pairs >= limit:
                break
            table = parquet.read_row_group(rg_idx)
            for row in table.to_pylist():
                if rows_seen < skip:
                    rows_seen += 1
                    continue
                if limit is not None and yielded_pairs >= limit:
                    break
                pair_index = rows_seen
                rows_seen += 1
                for side in sides:
                    audio_struct = row[f"audio{side}"]
                    wav, sr = _decode_audio_struct(audio_struct)
                    yield ClipRecord(
                        pair_index=pair_index,
                        side=side,
                        subset=row.get("subset", ""),
                        language_setting=row.get("language_setting", ""),
                        target_text=row.get("target_text", ""),
                        waveform=wav,
                        sample_rate=sr,
                    )
                yielded_pairs += 1
