"""SpeechJudge-Data streaming loader.

Yields one decoded audio clip at a time from the live HuggingFace dataset.
Each preference pair contributes TWO clips (audioA + audioB), each emitted
as a separate `ClipRecord` so the downstream feature extractor and cache
deal in flat units.

Why not yield pairs directly: the BT training loop assembles pairs from the
feature cache by `pair_id`, so the cache lookup needs per-clip granularity.
Keeping the loader flat also makes resume-from-checkpoint trivial (one
manifest entry per clip).

Schema this loader knows about is documented in docs/DATASETS.md, which was
auto-generated by scripts/00_inspect_dataset.py during Milestone 1.
"""

from __future__ import annotations

import io
from dataclasses import dataclass
from typing import Iterator, Literal

import numpy as np

DATASET_ID = "RMSnow/SpeechJudge-Data"
Side = Literal["A", "B"]
SPLITS = ("train", "dev", "test")


@dataclass(frozen=True)
class ClipRecord:
    """One audio clip from a SpeechJudge preference pair, pre-decoded."""

    pair_index: int                # row index in the original split
    side: Side                     # "A" or "B"
    subset: str                    # "regular" | "expressive"
    language_setting: str          # e.g. "zh2en"
    target_text: str               # text both A and B synthesize
    waveform: np.ndarray           # float32, mono, native sample rate
    sample_rate: int

    @property
    def clip_id(self) -> str:
        """Stable cache key. {split-tag is added by the extractor.}"""
        return f"{self.pair_index:08d}_{self.side}"

    def num_samples(self) -> int:
        return int(self.waveform.shape[0])

    def duration_seconds(self) -> float:
        return self.num_samples() / float(self.sample_rate)


def _decode_audio_field(audio_dict: dict) -> tuple[np.ndarray, int]:
    """Decode the HF Audio({path, bytes}) struct via soundfile.

    Raises ValueError with a clear message on malformed rows.
    """
    import soundfile as sf  # lazy: keeps module import cheap for tests

    raw = audio_dict.get("bytes")
    path = audio_dict.get("path")
    if raw is None:
        raise ValueError(
            f"Audio dict has no inline bytes (path={path!r}). "
            f"M1 inspection promised inline bytes; dataset schema may have changed."
        )
    wav, sr = sf.read(io.BytesIO(raw), dtype="float32", always_2d=False)
    if wav.ndim == 2:
        wav = wav.mean(axis=1).astype(np.float32, copy=False)
    return wav, int(sr)


def iter_clips(
    split: str = "train",
    limit: int | None = None,
    *,
    token: str | None = None,
    skip: int = 0,
    sides: tuple[Side, ...] = ("A", "B"),
) -> Iterator[ClipRecord]:
    """Stream-decode SpeechJudge clips.

    Args:
        split: dataset split, one of {"train", "dev", "test"}.
        limit: maximum number of PAIRS to yield (each contributes len(sides)
               clips). None = no limit.
        token: HF token; reads from env if None.
        skip: number of pairs to skip from the start of the split (for
              resume-from-checkpoint).
        sides: which sides to yield. Default both; ("A",) for one-sided runs.
    """
    if split not in SPLITS:
        raise ValueError(f"split={split!r} not in {SPLITS}")
    if any(s not in ("A", "B") for s in sides):
        raise ValueError(f"sides must contain only 'A'/'B'; got {sides!r}")

    from datasets import Audio, load_dataset  # type: ignore[import-not-found]

    ds = load_dataset(DATASET_ID, split=split, streaming=True, token=token)
    # Audio decoding via the datasets library requires torchcodec; we decode
    # via soundfile instead (already a hard dep).
    ds = ds.cast_column("audioA", Audio(decode=False))
    ds = ds.cast_column("audioB", Audio(decode=False))

    if skip:
        ds = ds.skip(skip)

    yielded_pairs = 0
    for offset, row in enumerate(ds):
        if limit is not None and yielded_pairs >= limit:
            break
        pair_index = skip + offset
        for side in sides:
            audio_field = row[f"audio{side}"]
            wav, sr = _decode_audio_field(audio_field)
            yield ClipRecord(
                pair_index=pair_index,
                side=side,
                subset=row.get("subset", ""),
                language_setting=row.get("language_setting", ""),
                target_text=row.get("target_text", ""),
                waveform=wav,
                sample_rate=sr,
            )
        yielded_pairs += 1
